export { QUERY, singleQUERY, MYFAV_QUERY } from './query';
export {
    CREATE_JOURNEY_MUTATION, search_QUERY, GET_LINESTRING,
    REGISTER_MUTATION, LOGIN_MUTATION, ADDFAV_MUTATION, DELFAV_MUTATION, CHANGEPASS_MUTATION, AUTHTOKEN_MUTATION, REPORT_MUTATION
} from "./mutation" 